server:
  port: 7081

spring:
  application:
    name: doctor-portal

eureka:
  client:
    register-with-eureka: false
#doctor-service:
#  ribbon:
#    listOfServers: localhost:9081,localhost:9082,localhost:9083